export { authAPI } from "./auth";
export { courseAPI } from "./course";
export { graphAPI } from "./graph";
export { noteAPI } from "./note";
export { quizAPI } from "./quiz";
export { progressAPI } from "./progress";
export { userCourseAPI } from "./userCourse";
export { postAPI, commentAPI } from "./community";
export { wrongQuestionAPI } from "./wrongQuestion";
export { reviewPlanAPI } from "./reviewPlan";
export { default as api } from "./apiClient";
